### ISSUE TITLE
App freezes on startup

### ISSUE THREAD

**Issue by Chaphasilor** [Bruhtek/jellyamp#17]
Hi there! I wanted to give the app a spin, and the onboarding worked pretty well and looked nice.

However, after finishing the onboarding, the loading spinner would spin for a few seconds before the whole app would freeze and not respond anymore even after waiting 30s.

Any ideas? Is there a way for me to send you logs?

**Comment by Bruhtek** [comment]
Hello!
To be perfectly honest, I don't actively work on the app anymore, ever since [Symfonium](https://symfonium.app/) app got good enough for me to daily use. It's very possible that there was some api change that has broken the app, but I should've indicated that in the readme.

If you are looking for a android Jellyfin music player, Symfonium is honestly the best you can get, costs about 5$ and worth every penny!
